/* global window */
window.GAME_DATA = {
  passThreshold: 0.7,
  modules: [
    {
      id: "html-doc",
      title: "Document skeleton & metadata",
      area: "HTML",
      topics: ["doctype", "html/head/body", "charset/viewport", "title/link/script", "comments"],
      questions: [
        {
          type: "mcq",
          topic: "Basics",
          prompt: "Which declaration should appear first in a modern HTML document?",
          options: ['<!DOCTYPE html>', '<html>', '<?xml version="1.0"?>', '<meta charset="utf-8">'],
          correctIndex: 0,
          explain: "<!DOCTYPE html> selects the standards mode and should be the very first line.",
        },
        {
          type: "tf",
          topic: "Head",
          prompt: "The <title> element affects the text shown in the browser tab and default bookmark label.",
          correct: true,
          explain: "<title> sets the document title shown in tabs, history, and search engine results snippets.",
        },
        {
          type: "order",
          topic: "Structure",
          prompt: "Order a minimal valid top-level outline (conceptual lines).",
          lines: ["<!DOCTYPE html>", "<html>", "<head>…</head>", "<body>…</body>", "</html>"],
          explain: "Doctype first, then html wrapper; head typically precedes body.",
        },
        {
          type: "gap",
          topic: "Encoding",
          prompt: 'Declare UTF-8 in HTML5 using: <meta charset="___">',
          answers: ["utf-8", "UTF-8"],
          explain: 'UTF-8 is the usual value; quotes may be single or double in HTML.',
        },
        {
          type: "mcq",
          topic: "Viewport",
          prompt: "Why include a responsive viewport meta tag?",
          options: [
            "So mobile browsers scale the layout to device width",
            "To disable JavaScript",
            "To load CSS faster",
            "To set the page language",
          ],
          correctIndex: 0,
          explain: "The viewport meta controls initial scale and width mapping on mobile browsers.",
        },
      ],
    },
    {
      id: "html-text",
      title: "Text, headings & inline semantics",
      area: "HTML",
      topics: ["h1–h6", "p", "br", "strong/em", "code/pre", "blockquote", "hr"],
      questions: [
        {
          type: "mcq",
          topic: "Headings",
          prompt: "Which heading should generally be unique and describe the page’s primary topic?",
          options: ["<h3>", "<h6>", "<h1>", "<title> only, never a heading"],
          correctIndex: 2,
          explain: "Use a single <h1> for the primary page heading; keep heading levels in sensible order.",
        },
        {
          type: "tf",
          topic: "Semantics",
          prompt: "<b> and <i> always carry stronger semantic meaning than <strong> and <em>.",
          correct: false,
          explain: "<strong>/<em> convey importance/emphasis; <b>/<i> are mostly presentational unless repurposed with roles.",
        },
        {
          type: "gap",
          topic: "Whitespace",
          prompt: "Preserve whitespace and line breaks for code samples with the ___ element (paired).",
          answers: ["pre", "PRE"],
          explain: "<pre> keeps whitespace; often paired with <code> for code blocks.",
        },
        {
          type: "mcq",
          topic: "Quotes",
          prompt: "Best element for a long quoted passage with optional attribution?",
          options: ["<q>", "<blockquote>", "<cite> alone", "<p class='quote'>"],
          correctIndex: 1,
          explain: "<blockquote> is for block quotations; <q> is for short inline quotes.",
        },
        {
          type: "match",
          topic: "Inline tags",
          prompt: "Match the inline element to its typical intent.",
          pairs: [
            { term: "<code>", def: "Fragment of computer code" },
            { term: "<cite>", def: "Title of a creative work" },
            { term: "<abbr>", def: "Abbreviation or acronym" },
            { term: "<mark>", def: "Highlighted reference text" },
          ],
          explain: "Inline semantics help assistive tech and search engines understand content.",
        },
      ],
    },
    {
      id: "html-links",
      title: "Links & URL basics",
      area: "HTML",
      topics: ["a[href]", "rel", "target", "download", "fragments", "mailto/tel"],
      questions: [
        {
          type: "mcq",
          topic: "Security",
          prompt: 'For links that open a new browsing context, which rel token helps mitigate tab-nabbing?',
          options: ["nofollow", "noopener", "prefetch", "modulepreload"],
          correctIndex: 1,
          explain: "Use rel=\"noopener\" (often paired with noreferrer) with target=\"_blank\".",
        },
        {
          type: "tf",
          topic: "Accessibility",
          prompt: "Link text like “click here” is considered accessible if the URL is descriptive.",
          correct: false,
          explain: "Link text should be meaningful out of context; avoid vague phrases.",
        },
        {
          type: "gap",
          topic: "Anchors",
          prompt: "Inline hyperlink element (tag name only, no brackets): ___",
          answers: ["a", "A"],
          explain: "The anchor element <a> creates hyperlinks with href.",
        },
        {
          type: "mcq",
          topic: "Navigation",
          prompt: "Which landmark wraps major navigation blocks?",
          options: ["<header>", "<nav>", "<section>", "<summary>"],
          correctIndex: 1,
          explain: "<nav> is intended for major navigation groups (not every single link list).",
        },
        {
          type: "order",
          topic: "Same-page jump",
          prompt: "Order the pieces to jump to an in-page section (conceptual).",
          lines: ['<a href="#faq">Read FAQ</a>', '<h2 id="faq">FAQ</h2>', "Browser scrolls to the target"],
          explain: "Fragment links point to id (or legacy name) anchors on the page.",
        },
      ],
    },
    {
      id: "html-lists-tables",
      title: "Lists & tables",
      area: "HTML",
      topics: ["ul/ol/li", "dl/dt/dd", "table/thead/tbody", "th/td", "caption", "colspan/rowspan"],
      questions: [
        {
          type: "mcq",
          topic: "Lists",
          prompt: "Which list type preserves meaning when item order matters (steps, rankings)?",
          options: ["<ul>", "<menu>", "<ol>", "<dl>"],
          correctIndex: 2,
          explain: "<ol> is for ordered sequences; <ul> is for unordered collections.",
        },
        {
          type: "tf",
          topic: "Tables",
          prompt: "Using <table> purely for page layout is a recommended modern practice.",
          correct: false,
          explain: "Tables should represent tabular data; layout belongs to CSS (flex/grid).",
        },
        {
          type: "gap",
          topic: "Description lists",
          prompt: "In a description list, terms are marked with ___ and descriptions with <dd>.",
          answers: ["dt", "DT"],
          explain: "<dl> groups <dt> terms with <dd> descriptions.",
        },
        {
          type: "mcq",
          topic: "Tables",
          prompt: "Which element improves table accessibility by naming the dataset?",
          options: ["<colgroup>", "<caption>", "<template>", "<figure>"],
          correctIndex: 1,
          explain: "<caption> provides a visible title for the table; still pair with headers scope where needed.",
        },
        {
          type: "match",
          topic: "Roles",
          prompt: "Match list-related elements to their roles.",
          pairs: [
            { term: "<ul>", def: "Unordered list container" },
            { term: "<ol>", def: "Ordered list container" },
            { term: "<li>", def: "List item" },
            { term: "<dl>", def: "Description list container" },
          ],
          explain: "Choosing the right list preserves semantics for users and parsers.",
        },
      ],
    },
    {
      id: "html-media",
      title: "Images, media & embedding",
      area: "HTML",
      topics: ["img", "srcset/sizes", "picture/source", "video/audio", "iframe", "SVG basics"],
      questions: [
        {
          type: "mcq",
          topic: "Images",
          prompt: "Which attribute provides accessible text when an image conveys meaning?",
          options: ["title", "alt", "loading", "decoding"],
          correctIndex: 1,
          explain: "Meaningful images need descriptive alt text; decorative images may use empty alt.",
        },
        {
          type: "tf",
          topic: "Lazy loading",
          prompt: 'loading="lazy" hints the browser to defer offscreen image loading.',
          correct: true,
          explain: "Native lazy loading reduces upfront network and CPU work for below-the-fold images.",
        },
        {
          type: "gap",
          topic: "Responsive images",
          prompt: "Element wrapping <source> variants for art direction: ___",
          answers: ["picture", "PICTURE"],
          explain: "<picture> lets you choose among <source> candidates plus an <img> fallback.",
        },
        {
          type: "mcq",
          topic: "Video",
          prompt: "Which attribute enables native video controls in supporting browsers?",
          options: ["autoplay", "controls", "loop", "muted"],
          correctIndex: 1,
          explain: "The controls attribute exposes play/pause UI (still consider accessibility and autoplay rules).",
        },
        {
          type: "order",
          topic: "Figure",
          prompt: "Order the typical figure pattern for an image with a caption.",
          lines: ["<figure>", "<img …>", "<figcaption>Caption</figcaption>", "</figure>"],
          explain: "<figcaption> documents the relationship between media and its caption.",
        },
      ],
    },
    {
      id: "html-forms",
      title: "Forms & user input",
      area: "HTML",
      topics: ["form/method/action", "label/for", "input types", "select/textarea", "button", "validation attrs"],
      questions: [
        {
          type: "mcq",
          topic: "Accessibility",
          prompt: "Best practice associating a label with an input?",
          options: [
            "Wrap input inside <label>",
            "Use for on <label> matching input id",
            "Place text before input with no markup",
            "Both A and B are valid patterns",
          ],
          correctIndex: 3,
          explain: "Explicit for/id or implicit nesting both create an accessible name association.",
        },
        {
          type: "tf",
          topic: "Security",
          prompt: "Client-side required and pattern attributes are sufficient to secure a form.",
          correct: false,
          explain: "Always validate on the server; client checks are hints and can be bypassed.",
        },
        {
          type: "gap",
          topic: "Grouping",
          prompt: "Group related fields and show a titled border using ___ / <legend>.",
          answers: ["fieldset", "FIELDSET"],
          explain: "<fieldset> groups controls; <legend> provides the group’s caption.",
        },
        {
          type: "mcq",
          topic: "Input types",
          prompt: "Which input type collects an email address with basic built-in validation hints?",
          options: ['type="text"', 'type="email"', 'type="search"', 'type="url"'],
          correctIndex: 1,
          explain: 'type="email" can trigger email-shaped validation in supporting browsers.',
        },
        {
          type: "match",
          topic: "Attributes",
          prompt: "Match validation-related attributes to what they influence.",
          pairs: [
            { term: "required", def: "Disallow empty submission" },
            { term: "minlength", def: "Minimum text length" },
            { term: "pattern", def: "Regex constraint for value" },
            { term: "max", def: "Upper bound for numeric/date inputs" },
          ],
          explain: "Constraint validation attributes improve UX but must be backed by server checks.",
        },
      ],
    },
    {
      id: "html-semantics",
      title: "Semantic structure & landmarks",
      area: "HTML",
      topics: ["header/footer", "main", "section/article", "aside", "address", "time"],
      questions: [
        {
          type: "mcq",
          topic: "Landmarks",
          prompt: "How many <main> elements should a document generally contain?",
          options: ["0", "1", "As many as needed", "Exactly 2"],
          correctIndex: 1,
          explain: "There should be at most one visible <main> per document (the primary content).",
        },
        {
          type: "tf",
          topic: "Article vs section",
          prompt: "<article> must only be used for blog posts.",
          correct: false,
          explain: "<article> is for self-contained compositions: posts, cards, comments, widgets, etc.",
        },
        {
          type: "gap",
          topic: "Time",
          prompt: "Machine-readable datetime on <time> uses the ___ attribute.",
          answers: ["datetime", "dateTime"],
          explain: "datetime pairs human-visible text with a parseable timestamp.",
        },
        {
          type: "mcq",
          topic: "Aside",
          prompt: "Typical use of <aside>?",
          options: [
            "Primary navigation only",
            "Tangentially related content (sidebars, pull quotes)",
            "Hidden templates",
            "Table headers",
          ],
          correctIndex: 1,
          explain: "<aside> is for content loosely tied to surrounding material.",
        },
        {
          type: "order",
          topic: "Outline",
          prompt: "Put these landmarks in a common page skeleton order.",
          lines: ["<header>…</header>", "<nav>…</nav>", "<main>…</main>", "<footer>…</footer>"],
          explain: "Exact order varies, but main sits between header/nav and footer in many layouts.",
        },
      ],
    },
    {
      id: "html-a11y-global",
      title: "Global attributes & accessibility hooks",
      area: "HTML",
      topics: ["id/class", "lang", "hidden/inert", "tabindex", "role (when needed)", "ARIA patterns"],
      questions: [
        {
          type: "mcq",
          topic: "Language",
          prompt: "Which attribute declares the natural language of an element’s text?",
          options: ["translate", "dir", "lang", "charset"],
          correctIndex: 2,
          explain: "lang helps pronunciation, hyphenation, and translation tools.",
        },
        {
          type: "tf",
          topic: "ARIA",
          prompt: "Prefer native HTML elements over ARIA roles when both can express the same UI.",
          correct: true,
          explain: "Native elements carry built-in semantics, keyboard behavior, and platform mappings.",
        },
        {
          type: "gap",
          topic: "Styling hooks",
          prompt: "Space-separated token list for CSS class selectors: attribute ___",
          answers: ["class", "CLASS"],
          explain: "class is for styling hooks; id must be unique for anchors/scripting.",
        },
        {
          type: "mcq",
          topic: "Focus",
          prompt: "Which tabindex value removes an element from sequential focus navigation?",
          options: ["0", "1", "-1", "auto"],
          correctIndex: 2,
          explain: "tabindex=\"-1\" makes an element programmatically focusable but not tab-stop by default.",
        },
        {
          type: "match",
          topic: "Attributes",
          prompt: "Match attribute to purpose.",
          pairs: [
            { term: "id", def: "Unique identifier within a document" },
            { term: "data-*", def: "Private custom data for scripts" },
            { term: "title", def: "Advisory information (often tooltip)" },
            { term: "contenteditable", def: "Allows direct user editing" },
          ],
          explain: "Global attributes apply broadly across many elements.",
        },
      ],
    },
    {
      id: "css-cascade",
      title: "Cascade, specificity & inheritance",
      area: "CSS",
      topics: ["origin/importance", "specificity", "inherit/initial/unset/revert", "layer @layer"],
      questions: [
        {
          type: "mcq",
          topic: "Specificity",
          prompt: "Which selector is most specific?",
          options: ["div", ".card", "#app", "*"],
          correctIndex: 2,
          explain: "IDs outweigh classes, which outweigh elements; * is zero specificity for the universal selector.",
        },
        {
          type: "tf",
          topic: "Inheritance",
          prompt: "All CSS properties inherit from parent to child by default.",
          correct: false,
          explain: "Many properties inherit (e.g., color), but box model properties typically do not unless inherited explicitly.",
        },
        {
          type: "gap",
          topic: "Important",
          prompt: "Declaration that beats normal cascade within same origin (keyword): ___!",
          answers: ["important", "IMPORTANT"],
          explain: "!important raises priority—use sparingly to avoid unmaintainable overrides.",
        },
        {
          type: "mcq",
          topic: "Layers",
          prompt: "What does @layer primarily help you organize?",
          options: ["Keyframes only", "Font files only", "The cascade priority of rule sets", "HTML outline"],
          correctIndex: 2,
          explain: "Cascade layers let you group styles and control override ordering intentionally.",
        },
        {
          type: "order",
          topic: "Cascade tie-break",
          prompt: "Order the tie-breakers after importance and origin (high-level, simplified).",
          lines: ["Specificity", "Source order (later wins)"],
          explain: "When specificity ties, the last declaration in source order typically wins.",
        },
      ],
    },
    {
      id: "css-selectors",
      title: "Selectors, combinators & pseudo",
      area: "CSS",
      topics: ["type/class/id/attr", ">, +, ~", ":hover/:focus/:focus-visible", "::before/after"],
      questions: [
        {
          type: "mcq",
          topic: "Combinators",
          prompt: "Which combinator selects direct children only?",
          options: [" ", ">", "+", "~"],
          correctIndex: 1,
          explain: "The child combinator > matches only immediate children, not deeper descendants.",
        },
        {
          type: "tf",
          topic: "Pseudo-elements",
          prompt: "::before creates an element that exists in the DOM tree like a real node.",
          correct: false,
          explain: "Pseudo-elements generate boxes as if inserted; they are not separate DOM nodes.",
        },
        {
          type: "gap",
          topic: "Attribute",
          prompt: "Selector for input whose type is exactly password: input[___=\"password\"]",
          answers: ["type", "TYPE"],
          explain: "Attribute selectors filter by attribute presence or exact/substring matches.",
        },
        {
          type: "mcq",
          topic: "Focus",
          prompt: "Which pseudo-class is designed for keyboard-like focus rings without mouse noise?",
          options: [":focus", ":active", ":focus-visible", ":target"],
          correctIndex: 2,
          explain: ":focus-visible helps show focus styles when they aid keyboard users.",
        },
        {
          type: "match",
          topic: "Pseudo",
          prompt: "Match pseudo to typical use.",
          pairs: [
            { term: ":hover", def: "Pointer is over the element" },
            { term: ":checked", def: "Toggle control is on" },
            { term: ":disabled", def: "Control cannot be used" },
            { term: ":nth-child()", def: "Select by sibling index pattern" },
          ],
          explain: "Pseudo-classes filter element states; pseudo-elements style generated subtrees.",
        },
      ],
    },
    {
      id: "css-box",
      title: "Box model & sizing",
      area: "CSS",
      topics: ["content/padding/border/margin", "box-sizing", "min/max/width/height", "overflow"],
      questions: [
        {
          type: "mcq",
          topic: "box-sizing",
          prompt: "Which box-sizing value makes width include padding and border?",
          options: ["content-box", "border-box", "inherit", "auto"],
          correctIndex: 1,
          explain: "border-box is the common reset-friendly sizing model for predictable layouts.",
        },
        {
          type: "tf",
          topic: "Margins",
          prompt: "Vertical margins of adjacent block siblings always add together (no collapse).",
          correct: false,
          explain: "Adjacent vertical margins can collapse in normal flow—an important layout gotcha.",
        },
        {
          type: "gap",
          topic: "Shorthand",
          prompt: "Shorthand that sets margin on all four sides at once: ___",
          answers: ["margin", "MARGIN"],
          explain: "margin can take 1–4 values mirroring top/right/bottom/left patterns.",
        },
        {
          type: "mcq",
          topic: "Overflow",
          prompt: "Which value clips content and hides scrollbars by default (no scroll)?",
          options: ["visible", "hidden", "scroll", "auto"],
          correctIndex: 1,
          explain: "hidden clips overflow; auto shows scrollbars only when needed.",
        },
        {
          type: "order",
          topic: "Box layers",
          prompt: "Order from center outward in the standard box model.",
          lines: ["Content", "Padding", "Border", "Margin"],
          explain: "Padding is inside the border; margin is outside.",
        },
      ],
    },
    {
      id: "css-type-color",
      title: "Typography & color",
      area: "CSS",
      topics: ["font-family/stack", "font-size/line-height", "font-weight", "text-align", "color"],
      questions: [
        {
          type: "mcq",
          topic: "Fonts",
          prompt: "Best practice for font-family lists?",
          options: [
            "Use only one font with no fallbacks",
            "End with a generic family like serif or sans-serif",
            "Always use quotes around generic names",
            "Never include web fonts",
          ],
          correctIndex: 1,
          explain: "Generic families ensure the UA can pick a sensible fallback.",
        },
        {
          type: "tf",
          topic: "Units",
          prompt: "rem is relative to the root element’s font size.",
          correct: true,
          explain: "rem scales with the document root, unlike em which uses the element’s font size.",
        },
        {
          type: "gap",
          topic: "Color",
          prompt: "Function for red/green/blue with optional alpha: ___()",
          answers: ["rgb", "RGBA", "rgba", "RGB"],
          explain: "Modern syntax supports rgb( r g b / a ) with space-separated components.",
        },
        {
          type: "mcq",
          topic: "Line height",
          prompt: "Unitless line-height like 1.5 is computed relative to what?",
          options: [
            "Viewport width",
            "The element’s own font size",
            "Parent width",
            "Root margin",
          ],
          correctIndex: 1,
          explain: "Unitless line-height multiplies the element’s computed font size.",
        },
        {
          type: "match",
          topic: "Text props",
          prompt: "Match property to effect.",
          pairs: [
            { term: "letter-spacing", def: "Space between characters" },
            { term: "text-transform", def: "Case folding like uppercase" },
            { term: "text-decoration", def: "Underlines/overlines/line-through" },
            { term: "white-space", def: "Wrapping and whitespace preservation" },
          ],
          explain: "Typography properties combine to control readability and rhythm.",
        },
      ],
    },
    {
      id: "css-bg-border",
      title: "Backgrounds, borders & effects",
      area: "CSS",
      topics: ["background-*", "border-radius", "outline vs border", "box-shadow", "filter"],
      questions: [
        {
          type: "mcq",
          topic: "Focus",
          prompt: "Which outline feature makes it ideal for accessible focus rings?",
          options: [
            "It always increases layout width like border",
            "It doesn’t affect layout and can sit outside border",
            "It cannot follow border-radius",
            "It replaces border entirely",
          ],
          correctIndex: 1,
          explain: "outline draws without affecting box size; combine thoughtfully with :focus-visible.",
        },
        {
          type: "tf",
          topic: "Gradients",
          prompt: "linear-gradient() is a background-image, not a color keyword.",
          correct: true,
          explain: "Gradients are image values used in background-image (or border-image contexts).",
        },
        {
          type: "gap",
          topic: "Radius",
          prompt: "Property that rounds box corners: border-___",
          answers: ["radius", "RADIUS"],
          explain: "border-radius can take multiple radii for elliptical corners.",
        },
        {
          type: "mcq",
          topic: "Shadows",
          prompt: "Which property draws a shadow around the entire element’s box?",
          options: ["text-shadow", "box-shadow", "filter: blur()", "outline-offset"],
          correctIndex: 1,
          explain: "box-shadow follows the border box; text-shadow applies to glyphs.",
        },
        {
          type: "order",
          topic: "Stacking context cues",
          prompt: "Put these from typically “back” to “front” in a simple painted mental model.",
          lines: ["Background color", "Background image", "Border", "Content"],
          explain: "Painting order is nuanced, but this captures the common mental stack.",
        },
      ],
    },
    {
      id: "css-layout-flow",
      title: "Display, flow & positioning",
      area: "CSS",
      topics: ["block/inline/inline-block", "position", "z-index", "float (legacy)", "inset offsets"],
      questions: [
        {
          type: "mcq",
          topic: "Positioning",
          prompt: "Which position value removes an element from normal flow and anchors to the viewport?",
          options: ["relative", "absolute", "fixed", "static"],
          correctIndex: 2,
          explain: "fixed is viewport-relative; absolute is containing-block-relative.",
        },
        {
          type: "tf",
          topic: "z-index",
          prompt: "z-index always works on position: static elements.",
          correct: false,
          explain: "z-index applies to positioned elements and flex/grid items among other cases—static is special.",
        },
        {
          type: "gap",
          topic: "Offsets",
          prompt: "Logical property for both left and right offsets together (modern): inset-___",
          answers: ["inline", "INLINE"],
          explain: "inset-inline sets start/end in the inline axis; physical top/left still exist too.",
        },
        {
          type: "mcq",
          topic: "Display",
          prompt: "Which display value creates a block container that flows inline with text?",
          options: ["block", "inline", "inline-block", "contents"],
          correctIndex: 2,
          explain: "inline-block is a block box that participates in an inline formatting context.",
        },
        {
          type: "match",
          topic: "Position",
          prompt: "Match position value to behavior (simplified).",
          pairs: [
            { term: "static", def: "Normal flow default" },
            { term: "relative", def: "Offset from normal position; preserves space" },
            { term: "absolute", def: "Out of flow; positions vs containing block" },
            { term: "sticky", def: "Hybrid: scroll until threshold then fixed-like" },
          ],
          explain: "Positioning interacts tightly with containing blocks and overflow clipping.",
        },
      ],
    },
    {
      id: "css-flex",
      title: "Flexbox layout",
      area: "CSS",
      topics: ["flex container/axes", "justify-content", "align-items", "flex-wrap", "flex shorthand", "gap"],
      questions: [
        {
          type: "mcq",
          topic: "Axes",
          prompt: "Main axis direction on a flex container is set with:",
          options: ["align-items", "flex-direction", "flex-wrap", "align-content"],
          correctIndex: 1,
          explain: "flex-direction establishes main axis orientation (row/column and reverse variants).",
        },
        {
          type: "tf",
          topic: "gap",
          prompt: "gap on a flex container only works if flex-wrap is wrap.",
          correct: false,
          explain: "gap separates items even in a single line; wrapping changes line packing, not gap availability.",
        },
        {
          type: "gap",
          topic: "Alignment",
          prompt: "Distribute extra space along the main axis: ___-content",
          answers: ["justify", "JUSTIFY"],
          explain: "justify-content aligns items along the main axis; align-items on the cross axis.",
        },
        {
          type: "mcq",
          topic: "Growth",
          prompt: "Which flex item property defines how free space is allocated for growth?",
          options: ["order", "flex-grow", "flex-basis", "align-self"],
          correctIndex: 1,
          explain: "flex-grow is a ratio; combine with flex-basis and flex-shrink via flex shorthand.",
        },
        {
          type: "order",
          topic: "Common patterns",
          prompt: "Order steps to center a single flex child both ways in a full viewport hero.",
          lines: [
            "Make container min-height: 100vh (or full area)",
            "Set display: flex",
            "Set justify-content: center",
            "Set align-items: center",
          ],
          explain: "Centering uses main/cross alignment on the container (or margin:auto tricks).",
        },
      ],
    },
    {
      id: "css-grid",
      title: "Grid layout",
      area: "CSS",
      topics: ["grid-template-*", "fr", "minmax()", "grid areas", "auto-fit/auto-fill"],
      questions: [
        {
          type: "mcq",
          topic: "Tracks",
          prompt: "Which unit splits free space after fixed tracks among flexible tracks?",
          options: ["px", "%", "fr", "ch"],
          correctIndex: 2,
          explain: "fr distributes remaining space in grid definitions.",
        },
        {
          type: "tf",
          topic: "Placement",
          prompt: "grid-column: 1 / -1 spans from the first line to the last line of the explicit grid.",
          correct: true,
          explain: "Negative numeric lines count from the end; -1 is the last line.",
        },
        {
          type: "gap",
          topic: "Templates",
          prompt: "Name template areas on the container with: grid-___-areas",
          answers: ["template", "TEMPLATE"],
          explain: "grid-template-areas provides a readable ASCII map of regions.",
        },
        {
          type: "mcq",
          topic: "Sizing",
          prompt: "minmax(200px, 1fr) means each track is at least 200px and can grow to:",
          options: ["0", "1fr of remaining space", "100vw always", "auto content only, never grow"],
          correctIndex: 1,
          explain: "minmax sets a floor and a flexible ceiling using fr where available.",
        },
        {
          type: "match",
          topic: "Functions",
          prompt: "Match grid helper to idea.",
          pairs: [
            { term: "repeat()", def: "Expand a track list pattern" },
            { term: "minmax()", def: "Clamp a track between min and max" },
            { term: "fit-content()", def: "Shrink-wrap with a cap" },
            { term: "auto-fill", def: "As many columns as fit, possibly empty tracks" },
          ],
          explain: "Grid track sizing functions build responsive columns without many media queries.",
        },
      ],
    },
    {
      id: "css-responsive",
      title: "Responsive design & units",
      area: "CSS",
      topics: ["media queries", "container queries", "vw/vh/vi/vb", "clamp()", "logical properties"],
      questions: [
        {
          type: "mcq",
          topic: "Media queries",
          prompt: "Classic responsive breakpoint adjusts rules based on:",
          options: ["DOM events only", "viewport/media features", "server headers", "z-index"],
          correctIndex: 1,
          explain: "@media (min-width: …) is the traditional viewport-based breakpoint tool.",
        },
        {
          type: "tf",
          topic: "Units",
          prompt: "100vw always equals the visible scrollbar-inclusive inner width on all browsers.",
          correct: false,
          explain: "vw/vh quirks exist around scrollbars and mobile UI; test carefully.",
        },
        {
          type: "gap",
          topic: "Clamp",
          prompt: "Function that picks a preferred value bounded by min and max: ___()",
          answers: ["clamp", "CLAMP"],
          explain: "clamp(min, preferred, max) is ideal for fluid type and spacing.",
        },
        {
          type: "mcq",
          topic: "Containers",
          prompt: "Container queries let styles respond primarily to:",
          options: ["The root font size", "A parent element’s size", "GPU memory", "HTTP cache"],
          correctIndex: 1,
          explain: "Use @container after defining a containment context on an ancestor.",
        },
        {
          type: "order",
          topic: "Mobile-first",
          prompt: "Order a simple mobile-first CSS strategy.",
          lines: [
            "Base styles for small screens",
            "Add @media (min-width: …) overrides for larger screens",
            "Avoid duplicating entire stylesheets per device",
          ],
          explain: "Mobile-first grows complexity upward with min-width queries.",
        },
      ],
    },
    {
      id: "css-motion",
      title: "Transitions, transforms & animation",
      area: "CSS",
      topics: ["transition-*", "@keyframes", "animation-*", "transform", "will-change (careful)"],
      questions: [
        {
          type: "mcq",
          topic: "Transitions",
          prompt: "Which property lists the CSS properties to interpolate when a value changes?",
          options: ["transition-duration", "transition-property", "animation-name", "transform-origin"],
          correctIndex: 1,
          explain: "transition-property names what changes should animate (or use all cautiously).",
        },
        {
          type: "tf",
          topic: "Transforms",
          prompt: "transform creates a containing block for all descendants’ fixed positioning.",
          correct: false,
          explain: "Transforms create a containing block for fixed descendants in many browsers—know the interaction.",
        },
        {
          type: "gap",
          topic: "Keyframes",
          prompt: "Define reusable animation phases with @___",
          answers: ["keyframes", "KEYFRAMES"],
          explain: "@keyframes lists percentage or from/to steps.",
        },
        {
          type: "mcq",
          topic: "Performance",
          prompt: "Which is usually the cheapest to animate for smoothness?",
          options: ["top/left", "width/height", "opacity", "box-shadow blur radius"],
          correctIndex: 2,
          explain: "opacity and transform are commonly compositor-friendly; layout properties trigger reflow.",
        },
        {
          type: "match",
          topic: "Animation API",
          prompt: "Match property to role.",
          pairs: [
            { term: "animation-duration", def: "One cycle length" },
            { term: "animation-iteration-count", def: "How many repeats" },
            { term: "animation-direction", def: "normal/alternate playback" },
            { term: "animation-fill-mode", def: "Styles before/after active time" },
          ],
          explain: "Shorthand animation sets many of these at once.",
        },
      ],
    },
    {
      id: "css-variables-misc",
      title: "Custom properties, stacking & misc",
      area: "CSS",
      topics: ["--* variables", "inheritance of custom props", "isolation", "contain", "prefers-* queries"],
      questions: [
        {
          type: "mcq",
          topic: "Variables",
          prompt: "Custom properties are declared with names like:",
          options: ["$primary", "@primary", "--primary", "%primary"],
          correctIndex: 2,
          explain: "CSS variables use --name and are resolved with var().",
        },
        {
          type: "tf",
          topic: "Dark mode",
          prompt: "prefers-color-scheme can switch themes without JavaScript.",
          correct: true,
          explain: "Media features like prefers-color-scheme enable user-respecting themes.",
        },
        {
          type: "gap",
          topic: "Usage",
          prompt: "Function to reference a custom property with fallback: ___(--x, #000)",
          answers: ["var", "VAR"],
          explain: "var(--token, fallback) is resilient when a token is missing.",
        },
        {
          type: "mcq",
          topic: "Stacking",
          prompt: "Which property can create a new stacking context among other effects?",
          options: ["color", "opacity < 1 (common case)", "font-size", "text-indent"],
          correctIndex: 1,
          explain: "Many properties (opacity, transform, filter, isolation) can affect stacking contexts.",
        },
        {
          type: "order",
          topic: "Theming",
          prompt: "Order a practical CSS variable theme swap.",
          lines: [
            "Define tokens on :root (light defaults)",
            "Override tokens in [data-theme='dark'] or .dark",
            "Components consume tokens via var()",
          ],
          explain: "Central tokens make global theme changes predictable.",
        },
      ],
    },
    {
      id: "git-basics",
      title: "Git fundamentals & local workflow",
      area: "Git",
      topics: ["repo/init", "status/add/commit", "branch", "merge/conflicts", "checkout/switch"],
      questions: [
        {
          type: "mcq",
          topic: "Tracking",
          prompt: "Which command stages tracked or untracked file changes so they can be included in the next commit?",
          options: ["git push", "git add", "git clone", "git fetch"],
          correctIndex: 1,
          explain: "`git add` moves changes into the staging area; commits only include what is staged.",
        },
        {
          type: "tf",
          topic: "History",
          prompt: "A Git commit mainly records a snapshot of your project along with metadata such as author and message.",
          correct: true,
          explain: "Commits act like named snapshots in the repository history, not just diffs floating by themselves.",
        },
        {
          type: "gap",
          topic: "Inspection",
          prompt: "To see which files are modified, staged, or untracked, run: git ___",
          answers: ["status", "STATUS"],
          explain: "`git status` summarizes the working tree and staging area.",
        },
        {
          type: "mcq",
          topic: "Branches",
          prompt: "What is the main reason developers create a new branch before starting a feature?",
          options: [
            "To delete commit history permanently",
            "To isolate work from the main line of development",
            "To upload files directly to GitHub Pages",
            "To make merge conflicts impossible",
          ],
          correctIndex: 1,
          explain: "Branches let you work independently and merge changes back when they are ready.",
        },
        {
          type: "match",
          topic: "Commands",
          prompt: "Match each Git command to its typical use.",
          pairs: [
            { term: "git commit", def: "Create a new history snapshot from staged changes" },
            { term: "git branch", def: "List or create branch references" },
            { term: "git merge", def: "Combine histories from another branch" },
            { term: "git switch", def: "Move to another branch in a newer-friendly way" },
          ],
          explain: "A basic local workflow is usually status, add, commit, then branch and merge as needed.",
        },
      ],
    },
    {
      id: "github-collab",
      title: "GitHub collaboration & remote workflow",
      area: "GitHub",
      topics: ["remote/origin", "push/pull", "pull requests", "issues", "forks/review"],
      questions: [
        {
          type: "mcq",
          topic: "Remotes",
          prompt: "In many repositories, what does the remote name `origin` usually refer to?",
          options: [
            "A backup branch on your laptop",
            "The default package registry",
            "The primary remote repository URL you cloned from",
            "The first commit in project history",
          ],
          correctIndex: 2,
          explain: "`origin` is the conventional default name Git gives the remote you cloned from.",
        },
        {
          type: "tf",
          topic: "Pull requests",
          prompt: "A pull request is commonly used to discuss, review, and merge branch changes on GitHub.",
          correct: true,
          explain: "Pull requests bundle code review, comments, checks, and merge controls around a branch diff.",
        },
        {
          type: "gap",
          topic: "Sharing",
          prompt: "Upload your local branch commits to the remote with: git ___",
          answers: ["push", "PUSH"],
          explain: "`git push` sends local commits to a configured remote branch.",
        },
        {
          type: "order",
          topic: "Typical flow",
          prompt: "Order a common GitHub contribution flow.",
          lines: [
            "Create or switch to a feature branch locally",
            "Commit your work",
            "Push the branch to GitHub",
            "Open a pull request for review",
          ],
          explain: "Most collaborative GitHub work follows branch, commit, push, and pull request review.",
        },
        {
          type: "mcq",
          topic: "Issues",
          prompt: "What is a GitHub Issue best suited for?",
          options: [
            "Compiling CSS into production assets",
            "Tracking bugs, feature ideas, and task discussions",
            "Replacing all local Git commits",
            "Signing commits automatically in every repo",
          ],
          correctIndex: 1,
          explain: "Issues help teams track work, discuss bugs, and organize future improvements.",
        },
      ],
    },
  ],
};
